services:
  app:
    build:
      context: .
      target: final
      args:
        VERSION_TAG: cli-alpine3.20
        UUID: 1000
        GID: 1000
    ports:
      - 9000:9000
    volumes:
      - .:/app
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:14.13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  default:
    name: cotaai
    driver: bridge